"""att delete aplicacao table

Revision ID: 29a3c2a784ae
Revises: 9fdbaa7c43d5
Create Date: 2022-04-27 01:20:04.079027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a3c2a784ae'
down_revision = '9fdbaa7c43d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aplicacao', type_='foreignkey')
    op.drop_constraint(None, 'aplicacao', type_='foreignkey')
    op.drop_constraint(None, 'aplicacao', type_='foreignkey')
    op.create_foreign_key(None, 'aplicacao', 'vacina', ['id_vacina'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'aplicacao', 'vacinador', ['crm'], ['crm'], ondelete='CASCADE')
    op.create_foreign_key(None, 'aplicacao', 'vacinado', ['cns'], ['cns'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aplicacao', type_='foreignkey')
    op.drop_constraint(None, 'aplicacao', type_='foreignkey')
    op.drop_constraint(None, 'aplicacao', type_='foreignkey')
    op.create_foreign_key(None, 'aplicacao', 'vacinado', ['cns'], ['cns'])
    op.create_foreign_key(None, 'aplicacao', 'vacina', ['id_vacina'], ['id'])
    op.create_foreign_key(None, 'aplicacao', 'vacinador', ['crm'], ['crm'])
    # ### end Alembic commands ###
