"""Add Vacinado table

Revision ID: 43df3e699761
Revises: cf410b644ef3
Create Date: 2022-04-26 21:04:35.295632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43df3e699761'
down_revision = 'cf410b644ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacinado',
    sa.Column('cns', sa.String(length=15), nullable=False),
    sa.Column('cpf', sa.String(length=12), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('dtNascimento', sa.Date(), nullable=False),
    sa.Column('comorbidade', sa.Boolean(), nullable=False),
    sa.Column('qtdDose', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cns'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacinado')
    # ### end Alembic commands ###
