"""Add Vacinador table

Revision ID: 686863d333f6
Revises: 43df3e699761
Create Date: 2022-04-26 21:30:34.659907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686863d333f6'
down_revision = '43df3e699761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacinador',
    sa.Column('crm', sa.String(length=15), nullable=False),
    sa.Column('cpf', sa.String(length=12), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('dtNascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('crm'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacinador')
    # ### end Alembic commands ###
