"""Add data in aplicacao table

Revision ID: 9fdbaa7c43d5
Revises: bc045a00aa08
Create Date: 2022-04-26 22:25:58.376846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdbaa7c43d5'
down_revision = 'bc045a00aa08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aplicacao', sa.Column('data', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aplicacao', 'data')
    # ### end Alembic commands ###
