"""Add aplicacao table

Revision ID: bc045a00aa08
Revises: 686863d333f6
Create Date: 2022-04-26 22:13:07.702856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc045a00aa08'
down_revision = '686863d333f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm', sa.String(length=15), nullable=False),
    sa.Column('cns', sa.String(length=15), nullable=False),
    sa.Column('id_vacina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cns'], ['vacinado.cns'], ),
    sa.ForeignKeyConstraint(['crm'], ['vacinador.crm'], ),
    sa.ForeignKeyConstraint(['id_vacina'], ['vacina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aplicacao')
    # ### end Alembic commands ###
